"""
This type stub file was generated by pyright.
"""

import os
import sys
from ._base import Menu, MenuItem

def backend():  # -> Module("_dummy") | Module("_appindicator") | Module("_darwin") | Module("_gtk") | Module("_win32") | Module("_xorg"):
    """Returns the backend module."""
    ...

Icon = backend().Icon
